import { absoluteUrl } from "./seoConfig";

/** Path segment with brackets - use encoded form in HTML href when needed. */
const COMPANY_ICON_MEDIA_DIR = "/media/NST_-_Favicon_[Dark_Transparent]";
const COMPANY_ICON_MEDIA_DIR_ENCODED =
  "/media/NST_-_Favicon_%5BDark_Transparent%5D";

const COMPANY_ICON_BASE = `${COMPANY_ICON_MEDIA_DIR}/NST_-_Favicon_[Dark_Transparent]`;
const COMPANY_ICON_BASE_ENCODED = `${COMPANY_ICON_MEDIA_DIR_ENCODED}/NST_-_Favicon_%5BDark_Transparent%5D`;

/** Root favicons generated by scripts/generate-favicons.mjs */
const ROOT_FAVICONS = {
  ico: "/favicon.ico",
  png32: "/favicon-32x32.png",
  appleTouch: "/apple-touch-icon.png",
  webp128: "/company-icon-128.webp",
} as const;

export const COMPANY_ICON = {
  /** Sharp nav / small UI (generated 128px webp at public root) */
  nav: ROOT_FAVICONS.webp128,
  /** Media folder - 480px source */
  webp480: `${COMPANY_ICON_BASE}-480.webp`,
  webp480Encoded: `${COMPANY_ICON_BASE_ENCODED}-480.webp`,
  webp800: `${COMPANY_ICON_BASE}-800.webp`,
  /** Absolute URL for JSON-LD logo */
  webUrl: absoluteUrl(`${COMPANY_ICON_BASE}-480.webp`),
} as const;

export function companyIconLinks() {
  return [
    { rel: "icon", href: ROOT_FAVICONS.ico, sizes: "any" },
    { rel: "icon", type: "image/png", href: ROOT_FAVICONS.png32, sizes: "32x32" },
    { rel: "icon", type: "image/webp", href: COMPANY_ICON.webp480Encoded, sizes: "480x480" },
    { rel: "apple-touch-icon", href: ROOT_FAVICONS.appleTouch, sizes: "180x180" },
  ] as const;
}
